name: Build and Release (release branch only)

on:
  push:
    branches: [ release ]  # only run on Release Branch

jobs:
  build_release:
    if: github.ref == 'refs/heads/release'  # extra guard for manual runs
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: false
          lfs: true

      - name: Checkout MoonLight-API dependency
        uses: actions/checkout@v4
        with:
          repository: team-dustycrew/MoonLight-API
          path: MoonLight-API
          fetch-depth: 1
          token: ${{ secrets.API_READ_TOKEN }}

      - name: Prepare Dalamud dev libraries
        shell: pwsh
        run: |
          $dev = Join-Path $env:APPDATA 'XIVLauncher/addon/Hooks/dev'
          New-Item -ItemType Directory -Path $dev -Force | Out-Null
          $zip = Join-Path $env:RUNNER_TEMP 'dalamud.zip'
          Invoke-WebRequest -Uri 'https://goatcorp.github.io/dalamud-distrib/latest.zip' -OutFile $zip
          Expand-Archive -Path $zip -DestinationPath $dev -Force
          echo "DALAMUD_HOME=$dev" >> $env:GITHUB_ENV

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
          cache: true
          cache-dependency-path: |
            **/packages.lock.json

      - name: Restore (skip submodules)
        run: dotnet restore Moonlight/Moonlight.csproj

      - name: Build (Release, x64)
        run: dotnet build Moonlight/Moonlight.csproj -c Release -p:Platform=x64 --no-restore

      - name: Detect packaged zips
        id: artifacts
        shell: pwsh
        run: |
          $z = Get-ChildItem 'Moonlight/bin/x64/Release' -Recurse -Filter *.zip | % FullName
          if (-not $z) { throw "No package (.zip) found in Release output." }
          "files=$($z -join "`n")" >> $env:GITHUB_OUTPUT

      - name: Read plugin version from csproj
        id: version
        shell: pwsh
        run: |
          [xml]$c = Get-Content Moonlight/Moonlight.csproj
          $v = $c.Project.PropertyGroup.Version
          "version=$v" >> $env:GITHUB_OUTPUT

      - name: Create/force tag
        shell: bash
        run: |
          git tag -f v${{ steps.version.outputs.version }}
          git push -f origin v${{ steps.version.outputs.version }}

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.version.outputs.version }}
          name: v${{ steps.version.outputs.version }}
          prerelease: ${{ contains(steps.version.outputs.version, '-') }}
          generate_release_notes: true
          files: ${{ steps.artifacts.outputs.files }}

      - name: Notify Discord (webhook)
        if: success()
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          VERSION: ${{ steps.version.outputs.version }}
        shell: pwsh
        run: |
          if (-not $env:DISCORD_WEBHOOK_URL) { Write-Host 'No DISCORD_WEBHOOK_URL secret set; skipping.'; exit 0 }
          $repo = "${{ github.repository }}"
          $tag = "v$env:VERSION"
          $releaseUrl = "https://github.com/$repo/releases/tag/$tag"
          if ($env:VERSION -match '-') { $kind = 'Pre-release' } else { $kind = 'Release' }
          $content = "**$kind** Moonlight $tag is live.`n$releaseUrl"
          $payload = @{ content = $content; allowed_mentions = @{ parse = @() } } | ConvertTo-Json -Depth 4
          Invoke-RestMethod -Uri $env:DISCORD_WEBHOOK_URL -Method POST -ContentType 'application/json' -Body $payload

      - name: Notify Discord (failure)
        if: failure()
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        shell: pwsh
        run: |
          if (-not $env:DISCORD_WEBHOOK_URL) { Write-Host 'No DISCORD_WEBHOOK_URL secret set; skipping.'; exit 0 }
          $repo = "${{ github.repository }}"
          $branch = "${{ github.ref_name }}"
          $sha = "${{ github.sha }}"
          $short = if ($sha.Length -ge 7) { $sha.Substring(0,7) } else { $sha }
          $runUrl = "https://github.com/$repo/actions/runs/${{ github.run_id }}"
          $branchUrl = "https://github.com/$repo/tree/$branch"
          $content = "**Build failed** on branch $branch ($short).`nSee run:`n$runUrl`nBranch:`n$branchUrl"
          $payload = @{ content = $content; allowed_mentions = @{ parse = @() } } | ConvertTo-Json -Depth 4
          Invoke-RestMethod -Uri $env:DISCORD_WEBHOOK_URL -Method POST -ContentType 'application/json' -Body $payload